### ISSUE TITLE
load model from_pretrained Error

### ISSUE THREAD

**Issue by Acecy237** [yfyeung/CLSP#2]
AttributeError: 'CLSPModel' object has no attribute 'all_tied_weights_keys'. Did you mean: '_tied_weights_keys'?

**Comment by yfyeung** [comment]
I’ve tested loading the model on my side, and it works well. Here is my environment:

```
transformers: 4.57.1
torch: 2.7.0+cu126
python: 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0]
```

Could you please share your setup?

```
python -c "import transformers, torch, sys; \
print('transformers:', transformers.__version__); \
print('torch:', torch.__version__); \
print('python:', sys.version)"
```

**Comment by Acecy237** [comment]
Thanks for your reply!
I found it doesn't work with torch==2.9.0 and transformers==5.0.0
I’ve reconfigured the environment following your version, and it works now.
